version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
  sonarqube: syneki/sonarqube@1.0.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
      